version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_bankapi
    ports:
      - "5432:5432"
    volumes:
      - db_bankapi:/var/lib/postgresql/data

volumes:
  db_bankapi: